### ISSUE TITLE
How could I use a different date format.

### ISSUE THREAD

**Issue by yunleiz** [rfoltyns/log4j2-elasticsearch#16]
How could I control the date format output to elasticsearch.

Thanks.

**Comment by rfoltyns** [comment]
Since 1.3, `JacksonJsonLayout` uses [LogEventJacksonJsonMixIn](https://github.com/rfoltyns/log4j2-elasticsearch/blob/master/log4j2-elasticsearch-core/src/main/java/org/apache/logging/log4j/core/jackson/LogEventJacksonJsonMixIn.java) to control the shape and contents of `org.apache.logging.log4j.core.impl.Log4jLogEvent`.

By default, date is present in `timeInMillis` property which is of type long, but it can be changed if you create your own, custon mixin class:
```
package org.apache.logging.log4j.core.jackson;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import org.apache.logging.log4j.core.LogEvent;

@JsonSerialize(as = LogEvent.class)
public abstract class CustomLogEventMixIn extends LogEventJacksonJsonMixIn implements LogEvent {

    private static final long serialVersionUID = 1L;

    @JsonProperty
    @JsonSerialize(using = CustomDateSerializer.class)
    @Override
    public abstract long getTimeMillis();

}
```

and configure `JacksonJsonLayout` to replace the default `JacksonJsonMixIn` config for `org.apache.logging.log4j.core.LogEvent` in `log4j2.xml`:
```xml
<Elasticsearch name="APPENDER_NAME">
(...)
            <JacksonJsonLayout>
                <!-- let's override LogEvent mixin -->
                <JacksonMixIn mixInClass="org.apache.logging.log4j.core.jackson.CustomLogEventMixIn"
                              targetClass="org.apache.logging.log4j.core.LogEvent"/>
            </JacksonJsonLayout>
(...)
</Elasticsearch>
```

**Comment by rfoltyns** [comment]
@yunleiz Did the solution described above work for you?

**Comment by yassermog** [comment]
can you give example of using time stamp yyyy-mm-dd and time

**Comment by rfoltyns** [comment]
@yassermog you can easily produce it using config above, `@JsonProperty(name="date")`, following serializer:
```java

public class CustomDateSerializer extends JsonSerializer {

    @Override
    public void serialize(Object value, JsonGenerator gen, SerializerProvider serializers) throws IOException {
        gen.writeString(Instant.ofEpochMilli((Long) value).atOffset(ZoneOffset.UTC).format(DateTimeFormatter.ISO_LOCAL_DATE));
    }

}
```

and mappings if needed:
```json
"mappings": {
      "@date": {
        "type":   "date",
        "format": "strict_date"
      }
    }
  }
```

**Comment by yassermog** [comment]
I got this error 

> 
2019-08-29 15:15:41,983 main ERROR Cannot write item source: class org.apache.logging.log4j.core.time.MutableInstant cannot be cast to class java.lang.Long (org.apache.logging.log4j.core.time.MutableInstant is in unnamed module of loader 'app'; java.lang.Long is in module java.base of loader 'bootstrap') (through reference chain: org.apache.logging.log4j.core.impl.Log4jLogEvent["@timestamp"])
2019-08-29 15:15:41,983 Log4j2-TF-7-AsyncLoggerConfig-4 ERROR Cannot write item source: class org.apache.logging.log4j.core.time.MutableInstant cannot be cast to class java.lang.Long (org.apache.logging.log4j.core.time.MutableInstant is in unnamed module of loader 'app'; java.lang.Long is in module java.base of loader 'bootstrap') (through reference chain: org.apache.logging.log4j.core.impl.Log4jLogEvent["@timestamp"])
2019-08-29 15:15:41,985 Log4j2-TF-7-AsyncLoggerConfig-4 ERROR An exception occurred processing Appender elasticsearchAsyncBatch java.lang.NullPointerException
	at org.appenders.log4j2.elasticsearch.jest.JestBulkOperations.createBatchItem(JestBulkOperations.java:59)
	at org.appenders.log4j2.elasticsearch.AsyncBatchDelivery.add(AsyncBatchDelivery.java:76)

**Comment by yassermog** [comment]
```java
package com.example.log4j2demo;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import org.apache.logging.log4j.core.LogEvent;
import org.apache.logging.log4j.core.jackson.LogEventJacksonJsonMixIn;
import org.apache.logging.log4j.core.time.Instant;

@JsonSerialize(as = LogEvent.class)
public abstract class CustomLogEventMixIn extends LogEventJacksonJsonMixIn implements LogEvent {

    private static final long serialVersionUID = 1L;

    @JsonProperty("@timestamp")
    @JsonSerialize(using = CustomDateSerializer.class)
    @JsonIgnore(false)
    @Override
    public abstract Instant getInstant();

}
```

**Comment by yassermog** [comment]
if I change to  getTimeMillis
```java
 @JsonProperty("@timestamp")
    @JsonSerialize(using = CustomDateSerializer.class)
    @JsonIgnore(false)
    @Override
    public abstract long getTimeMillis(); 
```
I got this error 
```java 
2019-08-29 15:34:43,924 I/O dispatcher 1 WARN One or more of the items in the Bulk request failed, check BulkResult.getItems() for more information.
2019-08-29 15:34:43,925 I/O dispatcher 1 WARN Batch of 33 items failed. Redirecting to org.appenders.log4j2.elasticsearch.NoopFailoverPolicy
2019-08-29 15:34:44,761 I/O dispatcher 1 WARN One or more of the items in the Bulk request failed, check BulkResult.getItems() for more information.
2019-08-29 15:34:44,762 I/O dispatcher 1 WARN Batch of 5 items failed. Redirecting to org.appenders.log4j2.elasticsearch.NoopFailoverPolicy

```
and the log is not sent

**Comment by rfoltyns** [comment]
@yassermog In case of `getTimeMillis` (as suggested) - did you check the logs from your ES cluster?
Make sure that you got your mappings right. ES may not be able to parse the document without them.

In case of MutableInstant, class cast issues come from the custom serializer I've provided - notice `Instant.ofEpochMilli((Long) value)` in it's code. It's meant to work with long (and `timeMillis` value). Feel free to change it to work with MutableInstant as you expect.

**Comment by yassermog** [comment]
can you add @timestamp to take advantage to kibana visualization 
in this [file](https://github.com/rfoltyns/log4j2-elasticsearch/blob/76e58577792415f97dd4e84501a40407fce1b991/log4j2-elasticsearch-core/src/main/java/org/apache/logging/log4j/core/jackson/LogEventJacksonJsonMixIn.java#L46)
and the people make custom Serializer if they want to change dateformat

**Comment by rfoltyns** [comment]
@yassermog Glad to help 👍

I could consider changing the `timeMillis` to `@timestamp` by default in future releases, but I'd rather discuss it more broadly as it'd could be a breaking change for current users.

Current implementation already allows full flexibility in this area (Instant vs long, local date vs date time, etc.), so I would rather not rush it and explore the options in 1.5/2.0 release (~next year).

**Comment by gvrayden** [comment]
@rfoltyns I looked around a little bit, but couldn't find how to use `@timestamp` instead of `timeMillis`. Could you pls help ? 
Also I want to prefix all my batches with ```{ "create" : { "_index" : "some-index-name" } }``` is that possible  ?

Thanks in advance.

**Comment by rfoltyns** [comment]
@gvrayden Overriding `timeMillis` is described [in the comment above](https://github.com/rfoltyns/log4j2-elasticsearch/issues/16#issuecomment-475624291). Just use `@JsonProperty("@timestamp")` to get the desired field name.

As for prefixing batches with `{ "create" : { "_index" : "some-index-name" } }`, there's no support for that. Index is created automatically if it doesn't exist with name provided by `IndexName` or `RollingIndexName`. I'm not planning to add anything to `_bulk` request payload it that's what you're asking.

But..

It will be possible to define custom requests on startup since 1.5 - you'll be able to do literally any administrative/maintenance work you want in the setup phase. I'll push this feature in the next few weeks, but I don't know when it will be released (**possibly** end of the year).

**Comment by gvrayden** [comment]
@rfoltyns Thanks, I will give it a try to change the timestamp field.

**Comment by EhsanMo** [comment]
Hi, I used  "JacksonMixIn" tag, it works for timestamp, but when defined some VirtualProperty(s) alongside it, these properties do not appear in the output. Does anyone have any idea? we use version 1.5.2

**Comment by rfoltyns** [comment]
Hi @EhsanMo. By design, `JacksonMixIn` applies only to `org.apache.logging.log4j.core.LogEvent`.

`VirtualProperty`(-ies) is just an overlay on top of Log4j2 LogEvent class and a it's a Jackson `virtualProperties` property itself (see [`virtualProperties definition`](https://github.com/rfoltyns/log4j2-elasticsearch/blob/c936f8078a8049b60812894ac0228c398769d9dd/log4j2-elasticsearch-core/src/main/java/org/appenders/log4j2/elasticsearch/json/jackson/ExtendedLogEventJacksonJsonMixIn.java#L30)). This overlay allows you to define properties on your own, outside of `JacksonAnnotationIntrospector` scope.  By default, in this project, "power" is delegated to [Log4j2 Lookups](https://logging.apache.org/log4j/2.x/manual/lookups.html), so customisations to`VirtualProperty` are available only with :
* custom Log4j2 lookup like [this](https://github.com/rfoltyns/log4j2-elasticsearch-examples/commit/7d3e3904252ac9d41bf949adbbb45d6657a08c69)
* custom `ValueResolver` implementation to replace Log4j2Lookups
* custom `VirtualPropertyFilter` implementations (not relevant here)

I'm not planning any work in this scope, but I'm open for PRs.

**Comment by EhsanMo** [comment]
Thanks, maybe I could not explain the problem properly. These two does not work correctly when using in the same context, for example: 
`<JacksonJsonLayout>`
`                <VirtualProperty name="hostname" value="$${sys:hostname:-undefined}" />`
`                       <JacksonMixIn mixInClass="xyz.logging.CustomLogEventMixIn" targetClass="org.apache.logging.log4j.core.LogEvent"/>`
`            </JacksonJsonLayout>`
Only CustomLogEventMixIn works and there's no virtual property in logs. Am I using it correctly?

**Comment by rfoltyns** [comment]
@EhsanMo I just tested it with [log4j2-elasticsearch-examples](https://github.com/rfoltyns/log4j2-elasticsearch-examples/commit/bbfe69e5962d6122a23391b5157dcb653b18d9ce). Works perfectly fine.

Are you extending the `org.appenders.log4j2.elasticsearch.json.jackson.ExtendedLogEventJacksonJsonMixIn` class? `virtualProperties` definition was moved there from `LogEventJacksonJsonMixIn` in 1.5.
