### ISSUE TITLE
How to override LogEventJacksonJsonMixIn properly?

### ISSUE THREAD

**Issue by kevcodez** [rfoltyns/log4j2-elasticsearch#18]
I am trying to add two new properties to every log entry using a CustomLogEventMixIn.

```kotlin
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.annotation.JsonSerialize
import org.apache.logging.log4j.core.LogEvent
import org.apache.logging.log4j.core.jackson.LogEventJacksonJsonMixIn
import java.time.Instant

@JsonSerialize(`as` = LogEvent::class)
abstract class CustomLogEventMixIn : LogEventJacksonJsonMixIn() {

    @JsonProperty("@timestamp")
    fun getTimestamp(): Instant {
        return Instant.ofEpochMilli(this.timeMillis)
    }

    @JsonProperty
    fun getEnvironment(): String {
        return System.getenv("SPRING_PROFILES_ACTIVE")
    }

}
```

My log4j2.xml

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="WARN">
    <Appenders>
        <Console name="Console" target="SYSTEM_OUT">
            <PatternLayout pattern="%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"/>
        </Console>
        <Elasticsearch name="elasticsearchAsyncBatch">
            <JacksonJsonLayout>
                <JacksonMixIn mixInClass="de.ottonow.reporting.CustomLogEventMixIn"
                              targetClass="org.apache.logging.log4j.core.LogEvent"/>
            </JacksonJsonLayout>
            <RollingIndexName indexName="log4j2" pattern="yyyy-MM-dd" />
            <AsyncBatchDelivery>

                <JestHttp serverUris="https:/foobar/_bulk" />
            </AsyncBatchDelivery>
        </Elasticsearch>
    </Appenders>
    <Loggers>
        <Root level="info">
            <AppenderRef ref="Console"/>
            <AppenderRef ref="elasticsearchAsyncBatch"/>
        </Root>
    </Loggers>
</Configuration>
```

I would expect the two properties to be in every log entry, however, the properties never get to the index and I can't see them.

I am using Elasticsearch 7.

Any help is appreciated.

**Comment by rfoltyns** [comment]
Unfortunately, Jackson `MixIn`s don't work this way.

However, in this case, there are workarounds:

1. In order to use `Instant` as `@timestamp` , this worked for me (note, that @JsonIgnore(false) has to be present to include getter that was ignored in `LogEventJacksonJsonMixIn`):

```java
    @JsonProperty("@timestamp")
    @JsonIgnore(false)
    @Override
    public abstract Instant getInstant();
```

2. If you want to append additional properties, you can smuggle them using Log4j2 `ThreadContext` and:

-  use `LogEvent.getContextMap` if you want to decorate root level of `document.source`:

```java
    @JsonAnyGetter
    @JsonIgnore(false)
    @Override
    public abstract Map<String, String> getContextMap();
```
NOTE: it's deprecated, so if it gets removed, switch to `getContextData`

- use `LogEvent.getContextData` if you don't care about nesting:

```java
    @JsonSerialize(using = ContextDataSerializer.class)
    @JsonIgnore(false)
    @Override
    public abstract ReadOnlyStringMap getContextData();
```

`ContextDataSerializer` is considered private in `log4j-core:jar` - another argument for a custom one.

**Comment by Michenux** [comment]
I would like to flatten the context data object because i don't like contextData.<attribute> in the generated json.
I have tried to add @JsonUnwrapped but it does not work.

Any suggestions to remove contextData level in the generated json ?
