### ISSUE TITLE
PatternLayout patterns creating a JSON message are not sent correctly

### ISSUE THREAD

**Issue by burtoni** [rfoltyns/log4j2-elasticsearch#23]
I'm using a PatternLayout that specifies a number of fields and massages them into a JSON string in the log4j2.xml file (not in code):
```
<Elasticsearch name="JmeterRunlogESAppender" messageOnly="true">
      <IndexName indexName="jmeter-runlog-${date:yyyy.MM.dd}" />
      <PatternLayout>
        <alwaysWriteExceptions>false</alwaysWriteExceptions>
        <pattern>{"timestamp": "%d{yyyy-MM-dd'T'HH:mm:ss.SSS'Z'}{GMT+0}", "Level": "%p", "i_gn": "%X{group}", "i_tn": "%t", "i_tnu": "%X{threadnum}", "i_un": "%X{username}", "i_uid": "%X{userId}", "i_cid": "%X{companyId}", "i_cty": "%X{country}", "i_corr_id": "%X{correlationId}", "m": "%m%enc{%ex}{JSON}"}%n</pattern>
      </PatternLayout>
      <AsyncBatchDelivery batchSize="1000" deliveryInterval="2000">
        <JestHttp serverUris="http://${ESServer}:${ESPort}" />
      </AsyncBatchDelivery>
    </Elasticsearch>
```

This appears to cause failures sending as I see a number of messages in the log:
```
[INFO] 2019-08-07 17:07:57,994 I/O dispatcher 1 WARN One or more of the items in the Bulk request failed, check BulkResult.getItems() for more information.
[INFO] 2019-08-07 17:07:58,002 I/O dispatcher 1 WARN Batch of 19 items failed. Redirecting to org.appenders.log4j2.elasticsearch.NoopFailoverPolicy
[INFO] 2019-08-07 17:07:59,070 I/O dispatcher 1 WARN One or more of the items in the Bulk request failed, check BulkResult.getItems() for more information.
[INFO] 2019-08-07 17:07:59,071 I/O dispatcher 1 WARN Batch of 5 items failed. Redirecting to org.appenders.log4j2.elasticsearch.NoopFailoverPolicy
```

The following PatternLayout works correctly:
`<pattern>%m%n</pattern>`

I suspect it is related to the need to have the message *already* in JSON format as per https://github.com/rfoltyns/log4j2-elasticsearch/tree/master/log4j2-elasticsearch-core#raw-log-message. Is this a correct assumption? Can the appender handle PatternLayouts that create the JSON string on the fly?

**Comment by rfoltyns** [comment]
`messageOnly=true` would work only if you had your whole message in a JSON form logged via Logger. Above configuration will omit the layout pattern you specified as it uses Message.getFormattedMessage() (`%m`) as document body.

> Can the appender handle PatternLayouts that create the JSON string on the fly?

Current release (1.3.4) does not. It will since 1.3.5 onwards. This is caused by the default mapping type used in 1.3.4: `index`. ES 7 will create the mapping on the fly, but silently fail to index the documents. **ES 6 will work just fine** though.

Since 1.3.5, in order to get the above `PatternLayout` config to work, you'll have to: 
1. Add `mappingType` attribute. From what I understood from the Mapping API changes in ES 7, value MUST be `_doc`.
```<JestHttp serverUris="http://${ESServer}:${ESPort}" mappingType="_doc"/>```
2. Remove `messageOnly=true` config

1.3.5 should be out this week.

**Comment by burtoni** [comment]
OK, will try the above with the new version when it is ready. Thanks.

**Comment by burtoni** [comment]
Just to confirm, I was able to push messages to ES5 after removing messageOnly. Thanks for the advice.

**Comment by rfoltyns** [comment]
1.3.5 is out. `mappingType` is set to `index` by default. You can override it with the config mentioned above.
