### ISSUE TITLE
How to register additional jackson module on the JacksonJsonLayout?

### ISSUE THREAD

**Issue by haikal00** [rfoltyns/log4j2-elasticsearch#51]
As in title, is there a way to register jackson module, other than customize the existing class by extending it?
particularly this area:
https://github.com/rfoltyns/log4j2-elasticsearch/blob/master/log4j2-elasticsearch-core/src/main/java/org/appenders/log4j2/elasticsearch/JacksonJsonLayout.java#L138

for example, https://github.com/FasterXML/jackson-modules-java8
Thank you

**Comment by rfoltyns** [comment]
At the moment there's no other way.

But I'm open to PRs if you'd like to add support for configurable modules. I can add a method to make this extension easier and pave the way for later improvements. Most probably sth like:
```java
protected Builder configureModules(ObjectMapper)
```
called exactly where you suggested.

**Comment by haikal00** [comment]
This means to have list of jackson module being registered just like how Mixins is registered.
So user will include the module in the class path (maven pom dependency), and register that in the log4j2.xml?

**Comment by rfoltyns** [comment]
Yes, but rather more like virtual properties, not mixins. Mixins rely on `loadClass`and I'm not a fan on `clazz.newInstance()` here. Here, module instance should be ready to use once it's added to the builder via `withJacksonModules(JacksonModule[])`.

It's all about creating proper skeleton for this. `JacksonModule` interface maybe? `JacksonModule.applyTo(ObjectMapper)` should ensure enough flexibility and extensibility with following philosophy in mind: 

```Want to add a module? You have to provide an implementation on your own, but in exchange you can then customize the mapper any way you want```

Few more thoughts:

* `ExtendedLog4j2JsonModule` can be migrated as-is - let's just make sure that it's added to the default list and never replaced(!), because it sets up mixins required for serialization. Mixins can be overriden later with `JacksonMixIn`, so having it set up like that is not an issue. 

* `JacksonAfterburnerModuleConfigurer` may have to be migrated at some point as well (`afterburner` flag might be tricky though). `AfterburnerModule` class MUST be loaded ONLY if flag is set to `true`.

* only concern is the config order. I guess that this one should work for a start:

1. modules
2. mixins
3. virtual properties

**Comment by rfoltyns** [comment]
Custom module support will be released in 1.5.

**Comment by rfoltyns** [comment]
@haikal00 would you like to test the new functionality with a SNAPSHOT version to verify that it works as you expected?

**Comment by rfoltyns** [comment]
Released in 1.5.0.

Enjoy!
