### ISSUE TITLE
InvalidTypeNameException on invalid mappingType in ES 5

### ISSUE THREAD

**Issue by jmdopereiro** [rfoltyns/log4j2-elasticsearch#68]
Hi, I just run the jest example against ES 5 and got this exception

2021-03-22 17:19:15,650 main ERROR IndexTemplate not added: {"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: template is missing;"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: template is missing;"}
2021-03-22 17:19:15,680 main INFO Waiting for last items... 4s, 0 items enqueued
2021-03-22 17:19:16,237 I/O dispatcher 1 WARN One or more items failed. First error: errorType: invalid_type_name_exception, errorReason: Document mapping type name can't start with '_', found: [_doc]

**Comment by rfoltyns** [comment]
@jmdopereiro You need to specify `mappingType="index"` to override the new default - `_doc` since 1.5.

**Comment by jmdopereiro** [comment]
I guess that config goes into indexTemplate.json ? The log4j2-elasticsearch-jest-springboot example is using 1.4.0.

Thanks

**Comment by jmdopereiro** [comment]
Just changed the JestBufferedHttp mapping type to index and now I have documents in the index so I will close the ticket, thank a lot.

**Comment by rfoltyns** [comment]
No, it goes into `JestHttp` or `JestBufferedHttp` or `HCHttp` depending on which module you use. See [mappingType documentation for Jest](https://github.com/rfoltyns/log4j2-elasticsearch/tree/master/log4j2-elasticsearch-jest#http) and [HC](https://github.com/rfoltyns/log4j2-elasticsearch/tree/master/log4j2-elasticsearch-hc#hchttp-properties).

`log4j2-elastivsearch-jest` docs are still specifying `index` being the default. This is incorrect - it's `_doc` since [this commit](https://github.com/rfoltyns/log4j2-elasticsearch/commit/b90d7a4e0019b8b30ca208bf0307997f6d0fc46b)

**Comment by jmdopereiro** [comment]
`mappingType="index"` in the `<JestBufferedHttp>` element of log4j2.xml fixes this.

**Comment by rfoltyns** [comment]
If you're using `JestBufferedHttp` already, I'd highly recommend to switch to `log4j2-elasticsearch-hc` - it's a bit more optimized. Configuration is very similar and if you got your buffer pool config right, switching modules will require just a handful of minor changes.

**Comment by rfoltyns** [comment]
> The log4j2-elasticsearch-jest-springboot example is using 1.4.0.

Yeah, it lags behind a bit. I'll update it soon.

**Comment by jmdopereiro** [comment]
Thank you for your advices, for the moment I'm just trying to find the easiest way to start sending logs to ES from my spring applications (some are on spring-boot)
