### ISSUE TITLE
Update elasticsearch client

### ISSUE THREAD

**Issue by kardapoltsev** [rfoltyns/log4j2-elasticsearch#8]
HI! Do you have any plans to upgrade elasticsearch client up to 6.x?

**Comment by rfoltyns** [comment]
Absolutely, I'd love to do that (if I had to). The thing is that - current client versions are compatible with all of the latest ES cluster releases.
(Please correct me me if I'm wrong but)
log4j2-elasticsearch-jest works fine with 6.2.4 (I'll give you an update against 6.3.0 soon)
log4j2-elasticsearch5-bulkprocessor works fine with 5.x and 6.x
so, unless you have a feature request that requires the update, I feel really well with the versions that we're on ATM

**Comment by kardapoltsev** [comment]
Yes, it works but it brings unwanted dependencies to my project.

**Comment by rfoltyns** [comment]
Ok, makes sense. I'll see what I can do.
Which module gives you trouble? And which dependencies you'd like to get rid of?

**Comment by kardapoltsev** [comment]
We are using elasticsearch client v6.x in our project. I didn't try to force client v6 dependency but it doesn't seem to be a right way to deal with it IMHO.

I'd like to use `log4j2-elasticsearch5-bulkprocessor`.

**Comment by rfoltyns** [comment]
This is pretty nasty. Exclusion will not work as 5.6.9 and 6.x have incompatible `client.addTransportAddress` APIs. Plus, XPack requires more deps in provided scope since 6.3.0. There are a couple of options here:

1. I can add `log4j2-elasticsearch6-bulkprocessor` in 1.2 release (coming soon) with dependency to 6.2.4 or later
2. I can update the client to 6.x in `log4j2-elasticsearch5-bulkprocessor` - I'm not a fan of this, cause it will create similar problems to projects using client v5.x 
3. You could consider using `log4j2-elasticsearch-jest` in projects that use ES client v6.x as well

I'm leaning towards elasticsearch6 module, but what do you think about option 3 for now?

**Comment by rfoltyns** [comment]
@kardapoltsev I've added `log4j2-elasticsearch6-bulkprocessor` with dependency to `org.elasticsearch.client:transport:6.2.4`. I'll release it next week.

Would you like to test it against `1.2.0-SNAPSHOT`? If so, I'll put it in Maven repos over the weekend. As an alternative, you can build it yourself.

**Comment by kardapoltsev** [comment]
Sorry for the late response. Yes, I could test it if you still need it.

**Comment by rfoltyns** [comment]
Yes, please. I've just released `log4j2-elasticsearch6-bulkprocessor:1.2.0` with a dep to 6.2.4

**Comment by kardapoltsev** [comment]
Works for me, thanks.
