### ISSUE TITLE
Is it possible to deseriailze JSON within the message into properties?

### ISSUE THREAD

**Issue by Timmeey86** [rfoltyns/log4j2-elasticsearch#85]
Hi,

thanks for creating this great plugin, and it is a powerful one!

There is one thing which would be nice to have, and I'm not sure if it is or isn't supported already:
Imagine an application would create a log message like this using SLF4J:

    LOGGER.atInfo().log( ()-> "Test Message " + createObjectBuilder()
                                .add("key1", "value1")
                                .add("key2", 42)
                                .add("key3", Boolean.TRUE)
                                .build());

Log4j would receive this as the following message:

    Test Message {"key1":"value1","key2":42,"key3":true}

Is it possible to configure log4j2-elasticsearch in a way which submits "key1", "key2", "key3" as separate properties in addition to the message? It wouldn't matter much if they are stripped from or remain in the message itself, but being able to index these keys would be beneficial.

**Comment by rfoltyns** [comment]
Thank you for the good word :+1: 

Yes, it's possible.

With `messageOnly`, you can simply log any JSON you want. There are trade-offs however.

1. LogEvent properties will be omitted, because only Message is serialized (written as-is)
2. If you have a mix of regular messages and JSON messages, you will need two separate appenders and respective loggers to handle both cases.

If this is not what you expect, it can also be achieved with [VirtualProperty](https://github.com/rfoltyns/log4j2-elasticsearch/tree/master/log4j2-elasticsearch-core#virtual-properties) and Log4j2 `ThreadContext`.

**Comment by Timmeey86** [comment]
Alright, that helps, thanks!
